#!/usr/bin/env python3
"""S1b analysis -> RESULTS.md (tables regenerate above <!-- DISCUSSION -->;
the hand-written discussion below the marker is preserved).

Per run: ROP from the level set at the 2 s plotfiles, window = S1 rule
(max(first removal + 10 s, 0.3 t_end) -> t_end, snapped to plotfiles);
<dT_rem> = mean frozen H/(rho Cp) of cells voided in the window; T_top and
a_f at firing from spall.removal_events_csv rows (regime 1) in the window;
vol_factor = (V_cell/V0)^(1/m) for the IG draw; energy check
ROP*rho*Cp*<dT_rem>/q; max |ledger_err|.
"""
import glob
import importlib.util
import os
import re
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
S1 = os.path.join(os.path.dirname(HERE), "s1_surface_resolution")
sys.path.insert(0, S1)
sys.path.insert(0, HERE)
# S1's analyze.py shares this file's name: load it under its own module name.
_spec = importlib.util.spec_from_file_location("s1_analyze", os.path.join(S1, "analyze.py"))
_s1 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_s1)
load_pf, load_thermo, pct = _s1.load_pf, _s1.load_thermo, _s1.pct
from run_sweep import DEPTH, dz_tag  # noqa: E402
from run import CASES, MEIER_KEYS  # noqa: E402

RHO, CP = 2750.0, 790.0
Q = 2.06e6
M = 20.0
T0 = 293.15
MARK = "<!-- DISCUSSION -->"


def v0_of(case, dz_mm):
    return (dz_mm * 1e-3) ** 3 if case == "W-cell" else 1.0e-9


def analyze(case, dz_mm, P):
    dz = dz_mm * 1e-3
    N = int(round(DEPTH / dz))
    zc = (np.arange(N) + 0.5) * dz
    r = dict(case=case, dz=dz_mm)
    if not os.path.exists(P + ".done"):
        r["status"] = "missing"
        return r
    pfs = sorted(glob.glob(os.path.join(P, "*cell")),
                 key=lambda p: int(re.search(r"(\d+)cell$", p).group(1)))
    pd = [load_pf(p) for p in pfs]
    tp = np.array([d["t"] for d in pd])

    def zs(d):
        k = np.nonzero(~d["rem"])[0].max()
        return zc[k] + d["phi"][k]
    z = np.array([zs(d) for d in pd])
    ev = np.genfromtxt(P + "_removal_events.csv", delimiter=",", names=True, ndmin=1)
    fire = ev[ev["regime"] == 1]
    if fire.size == 0:
        r["status"] = "no removal"
        return r
    t_first = float(fire["time"][0])
    t_end = tp[-1]
    i0 = int(np.searchsorted(tp, max(t_first + 10.0, 0.3 * t_end) - 1e-9))
    i1 = len(tp) - 1
    im = i0 + int(np.argmin(np.abs(tp[i0:] - 0.5 * (tp[i0] + tp[i1]))))
    t0, t1, tm = tp[i0], tp[i1], tp[im]
    mh = 3600.0
    rop = (z[i0] - z[i1]) / (t1 - t0)
    w = pd[-1]["rem"] & ~pd[i0]["rem"]
    dT_rem = float(np.mean(pd[-1]["H"][w]) / (RHO * CP))
    fw = fire[(fire["time"] > t0) & (fire["time"] <= t1)]
    th = load_thermo(os.path.join(P, "thermo.dat"))
    vcell = dz * dz * (DEPTH / N)
    r.update(status="ok", t0=t0, t1=t1, depth=(DEPTH - z[-1]) * 1e3,
             rop=rop * mh, rop_a=(z[i0] - z[im]) / (tm - t0) * mh, rop_b=(z[im] - z[i1]) / (t1 - tm) * mh,
             dT_rem=dT_rem, n_cells=int(w.sum()),
             T_mean=float(np.mean(fw["T_top"])), T_p10=pct(fw["T_top"], 10), T_p90=pct(fw["T_top"], 90),
             a_mean=float(np.mean(fw["a_f"])), a_p10=pct(fw["a_f"], 10), a_p90=pct(fw["a_f"], 90),
             n_fire=int(fw.size),
             vf=(vcell / v0_of(case, dz_mm)) ** (1.0 / M) if case != "S-4p4" else float("nan"),
             energy=rop * RHO * CP * dT_rem / Q,
             ledger=float(np.max(np.abs(th["ledger_err"]))))
    return r


def cell_d_identical(pa, pb):
    fa = sorted(glob.glob(os.path.join(pa, "*cell", "Level_0", "Cell_D_*")))
    fb = sorted(glob.glob(os.path.join(pb, "*cell", "Level_0", "Cell_D_*")))
    if [os.path.relpath(x, pa) for x in fa] != [os.path.relpath(y, pb) for y in fb] or not fa:
        return False, 0
    return all(open(x, "rb").read() == open(y, "rb").read() for x, y in zip(fa, fb)), len(fa)


def main():
    out = os.path.join(HERE, "output")
    rows = []
    table = dict(CASES)
    table.update(MEIER_KEYS)
    for case, (dzs, _) in table.items():
        for dz in dzs:
            P = os.path.join(out, f"{case}_{dz_tag(dz)}")
            if os.path.isdir(P):
                rows.append(analyze(case, dz, P))
                r = rows[-1]
                print(case, dz, r.get("status"),
                      "" if r.get("status") != "ok" else
                      f"ROP {r['rop']:.3f}  T_fire {r['T_mean']:.1f}  dT_rem {r['dT_rem']:.1f}  "
                      f"a_f {r['a_mean'] * 1e6:.3f} um  E {r['energy']:.4f}", flush=True)
    same, nfiles = cell_d_identical(os.path.join(out, "W-def_dz1"), os.path.join(out, "W-cell_dz1"))

    L = ["# S1b: firing temperature under the production Weibull block\n",
         "Generated by `analyze.py`. S1 column (1 x 1 x N, 250 mm, Neumann-0), F1 beam "
         "(uniform q = 2.06 MW/m^2, alpha = 2000/m), dt = 1 ms (overshoot q*dt/(rho Cp dz) = "
         "0.47 / 0.95 / 1.9 / 3.8 K per step at dz = 2 / 1 / 0.5 / 0.25 mm), 60 s, 1 rank, "
         "sp_weibull top_cell local_thermoelastic, confining.p = 1 MPa, melt_aware on, "
         "follow_mask + energy ledger on. Weibull block (Meier): a0_gb = 20 um, a0_ig = 4 um, "
         "m = 20, seed = 12345 (expression microstructure: every cell is IG).\n",
         "**Window:** max(first removal + 10 s, 0.3 t_end) to t_end, snapped to the 2 s "
         "plotfiles. ROP = level-set recession; <dT_rem> = frozen H/(rho Cp) of cells voided "
         "in the window; T_top / a_f = `removal_events.csv` firing rows (regime 1) in the "
         "window (both firings of each cell); vol_factor = (V_cell/V0)^(1/20); "
         "E-check = ROP rho Cp <dT_rem>/q.\n",
         f"**W-cell dz = 1 mm vs W-def dz = 1 mm** (V0 = dz^3 = 1e-9 = default): Level_0 "
         f"Cell_D {'IDENTICAL' if same else 'DIFFERENT'} ({nfiles} files).\n",
         "| case | dz mm | V0 m^3 | vol_factor | window s | depth mm | ROP m/h (1st / 2nd) | "
         "<dT_rem> K | T_top at firing K mean [p10, p90] (n) | a_f um mean [p10, p90] | "
         "E-check | max abs ledger_err |",
         "|" + "---|" * 12]
    for r in rows:
        if r.get("status") != "ok":
            L.append(f"| {r['case']} | {r['dz']:g} | {r.get('status')} |" + " |" * 9)
            continue
        v0 = "a0 = 4.436 um scalar" if r["case"] == "S-4p4" else f"{v0_of(r['case'], r['dz']):.3g}"
        vf = "-" if not np.isfinite(r["vf"]) else f"{r['vf']:.4f}"
        L.append(f"| {r['case']} | {r['dz']:g} | {v0} | {vf} | {r['t0']:.0f}-{r['t1']:.0f} | "
                 f"{r['depth']:.1f} | {r['rop']:.3f} ({r['rop_a']:.3f} / {r['rop_b']:.3f}) | "
                 f"{r['dT_rem']:.1f} | {r['T_mean']:.1f} [{r['T_p10']:.1f}, {r['T_p90']:.1f}] ({r['n_fire']}) | "
                 f"{r['a_mean'] * 1e6:.3f} [{r['a_p10'] * 1e6:.3f}, {r['a_p90'] * 1e6:.3f}] | "
                 f"{r['energy']:.4f} | {r['ledger']:.1e} |")

    def seq(case):
        rs = sorted([r for r in rows if r["case"] == case and r.get("status") == "ok"], key=lambda r: -r["dz"])
        return rs
    L.append("\n**Firing-T drift per halving** (mean T_top at firing; dT_fire = T - 293.15 K):\n")
    for case in ("W-def", "W-cell", "W-seed"):
        rs = seq(case)
        parts = []
        for a, b in zip(rs, rs[1:]):
            da, db = a["T_mean"] - T0, b["T_mean"] - T0
            parts.append(f"{a['dz']:g} -> {b['dz']:g} mm: {b['T_mean'] - a['T_mean']:+.1f} K "
                         f"({(db - da) / da * 100:+.2f}% of dT_fire)")
        L.append(f"- {case}: " + ("; ".join(parts) if parts else "n/a"))
    text = "\n".join(L) + "\n"
    res = os.path.join(HERE, "RESULTS.md")
    disc = f"\n{MARK}\n\n## Discussion\n\n(to be written)\n"
    if os.path.exists(res) and MARK in open(res).read():
        disc = "\n" + MARK + open(res).read().split(MARK, 1)[1]
    open(res, "w").write(text + disc)
    print("wrote", res)


if __name__ == "__main__":
    main()
